version: "1.0.0"

services:
  mysql:
    image: mysql:5.7.31
    container_name: "flight_mysql"
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8 --collation-server=utf8_unicode_ci
    restart: always
    ports:
      - 3313:3306
    environment:
      MYSQL_ROOT_PASSWORD: FlightSecret
      MYSQL_DATABASE: elbeg
      MYSQL_USER: root
      MYSQL_PASSWORD: FlightSecret
    volumes:
      - mysql:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: "flight_phpmyadmin"
    restart: always
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
      - PMA_PORT=3306
      - PMA_USER=root
      - PMA_PASSWORD=FlightSecret
    links:
      - mysql
    ports:
      - 8093:80

volumes:
  mysql:
